version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: devops/nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./devops/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./devops/nginx/certbot/conf:/etc/letsencrypt
      - ./devops/nginx/certbot/www:/var/www/certbot
    expose:
      - '80'
      - '443'
    command: '/bin/sh -c ''while :; do sleep 12h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./devops/nginx/certbot/conf:/etc/letsencrypt
      - ./devops/nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot --webroot-path=/var/www/certbot; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
