services:
  gatee-api-blue:
    image: ${CI_REGISTRY}/gatee-api:blue
    container_name: gatee-api-blue
    ports:
      - "8080:8080"
    environment:
      - ENV=prod
    env_file:
      - devops/.env
    networks:
      - gatee-net

networks:
  gatee-net:
    external: true
