services:
  gatee-api-green-01:
    image: ${CI_REGISTRY}/gatee-api:green
    container_name: gatee-api-green-01
    ports:
      - "8082:8080"
    environment:
      - ENV=prod
    env_file:
      - devops/.env
    networks:
      - gatee-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
  gatee-api-green-02:
    image: ${CI_REGISTRY}/gatee-api:green
    container_name: gatee-api-green-02
    ports:
      - "8083:8080"
    environment:
      - ENV=prod
    env_file:
      - devops/.env
    networks:
      - gatee-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
  gatee-nodejs-green:
    container_name: gatee-nodejs-green
    image: ${CI_REGISTRY}/gatee-nodejs:green
    ports:
      - "3001:3000"
    networks:
      - gatee-net

networks:
  gatee-net:
    external: true
